name: CI

on:
  push:
    branches: [main, robot_CI]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Check pylint
        run: poetry run pylint **/*.py *.py
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Activate Flask and keep it on
        run: poetry run flask run &
      - name: Run end-to-end tests with Robot Framework
        run: poetry run robot tests
      - uses: superfly/flyctl-actions/setup-flyctl@v1
        if: ${{ github.event_name == 'push' }}
      - run: poetry run flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' }}
